FROM mhart/alpine-node

RUN apk add --update python build-base

# Create app directory
RUN mkdir -p /usr/src/app && echo "Tattva Watchloop"
COPY package.json /usr/src/app/
WORKDIR /usr/src/app
RUN npm install
COPY . /usr/src/app/

EXPOSE 9090

WORKDIR /usr/src/app
# CMD ["npm", "run", "dwatch" "9090"]
CMD ["node", "./bin/distwatchloop", "9090"]
