FROM mhart/alpine-node

RUN apk add --update python build-base

# Create app directory
RUN mkdir -p /usr/src/app && echo "Tattva Watchloop"
COPY . /usr/src/app/
WORKDIR /usr/src/app
RUN npm install

EXPOSE 8091

WORKDIR /usr/src/app
#CMD ["npm", "run", "processor" "8091"]
CMD ["node", "./bin/processor", "8091"]
